apiVersion: helm.toolkit.fluxcd.io/v2beta2 # <-- FIX #1: Correct API version
kind: HelmRelease
metadata:
  name: kyverno
  namespace: security
spec:
  interval: 1h
  chart:
    spec:
      chart: kyverno
      sourceRef:
        kind: HelmRepository
        name: kyverno
      version: "3.2.x" # This is fine, it will pick the latest 3.2 patch
  values:
    # Your existing resource requests
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi

    # --- FIX #2: Point to the official k8s-maintained kubectl image ---
    cleanupJobs:
      image:
        registry: registry.k8s.io # Official K8s registry
        repository: kubectl # Official repository name
        tag: "v1.28.5" # Official tag (note the 'v' prefix)
    # ----------------------------------------------------------------
