apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kyverno
  namespace: security
spec:
  interval: 1h
  chart:
    spec:
      chart: kyverno
      sourceRef:
        kind: HelmRepository
        name: kyverno
      version: "3.2.x"
  values:
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi

    # --- ADD THIS BLOCK TO FIX THE PULL ERROR ---
    # This overrides the cleanup job image to pull from AWS ECR
    # instead of Docker Hub, avoiding rate limits.
    cleanupJobs:
      image:
        registry: public.ecr.aws
        repository: bitnami/kubectl
        tag: "1.28.5" # Use the same tag it was already failing to pull
    # ------------------------------------------
