apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kyverno
  namespace: security
spec:
  interval: 1h
  chart:
    spec:
      chart: kyverno
      sourceRef:
        kind: HelmRepository
        name: kyverno
      version: "3.2.x"
  values:
    # Your existing resource requests
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi

    # --- FIX #2: Point to the official k8s-maintained kubectl image ---
    cleanupJobs:
      image:
        registry: registry.k8s.io
        repository: kubectl
        tag: "v1.28.5"
    # ----------------------------------------------------------------
