apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: monitoring-flux-applier-cluster-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: flux-applier
    namespace: monitoring
# This ClusterRoleBinding gives the flux-applier ServiceAccount
# cluster-admin permissions in the monitoring namespace, which
