apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: grafana-charts
  namespace: cluster-config # Keeping repos central is best practice
spec:
  interval: 1h
  url: https://grafana.github.io/helm-charts
