apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: loki
      version: "6.29.0"
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
        namespace: cluster-config
      interval: 15m
  values:
    # --- Your custom values start here ---
    deploymentMode: SingleBinary

    singleBinary:
      replicas: 1

    # Disable scalable components since we are using SingleBinary
    write:
      replicas: 0
    read:
      replicas: 0
    backend:
      replicas: 0

    # Disable caching for lighter resource usage
    chunksCache:
      enabled: false
    resultsCache:
      enabled: false

    test:
      enabled: false

    loki:
      auth_enabled: false
      commonConfig:
        replication_factor: 1
      storage:
        type: filesystem
        filesystem:
          directory: /var/loki/chunks
      useTestSchema: true
